#!/bin/bash

# M107 in your G code program will run the Linux commands in this
# shell script "batch" file, passing the P and Q variables as command
# line arguments.

# M code to set EXTRUDER 0 fan on at set point

echo "Usage: M106 Pn - where n is the speed %"

# give the command line arguments descriptive names
P=$1
#Q=$2

# first bump the fan to 100% to get it started
halcmd sets ext0-fan-SP 100
sleep 0.5

# set the tan to the desired speed (%)
halcmd sets ext0-fan-SP P

# if a M1nn command exits with nonzero status,
# the gcode program exits.  So always exit 0.
exit 0 ;# 0 for success