#!/bin/bash

# M109 in your G code program will run the Linux commands in this
# shell script "batch" file, passing the P and Q variables as command
# line arguments.

# M code to set BED temperature and wait until temperature has been reached

echo "Usage: M190 Pn - where n is the temperature"

# give the command line arguments descriptive names
P=$1
#Q=$2

TOLERANCE=0.5

PV=$(halcmd gets bed-PV)

halcmd sets bed-SP $P

#bash cannot do floating point comparison

SP=$(echo "($P-$TOLERANCE)"| bc -l)
delta=`echo "scale=3; ($PV < $SP)"| bc -l`


while [ "$delta" != "0" ]
do
  PV=$(halcmd gets bed-PV)
  delta=`echo "scale=3; ($PV < $SP)"| bc -l`
  sleep 1
done

echo "Temperature reached"


# if a M1nn command exits with nonzero status,
# the gcode program exits.  So always exit 0.
exit 0 ;# 0 for success