#!/usr/bin/env python2

# Note! Change the above "python2" to "python" is not using Arch Linux

# M code to set Fan speed
# M107 in your G code program will run the python code in this file, 
# passing the P and Q variables as command line arguments.

import sys
import hal

Mcode = 'M107'
usage = 'Fan off'
pin = 'SP'
SP_signal = 'ext0-cooling-SP'

h = hal.component(Mcode)

print ("Usage: " + Mcode)

# P and Q command line arguments
P = sys.argv[1]
Q = sys.argv[2]

print ('Setting ' + usage)

h.newpin(pin, hal.HAL_FLOAT, hal.HAL_OUT)
hal.connect(Mcode + '.' + pin, SP_signal)

h[pin] = 0

